import type { BuildingId, UnitId } from "@ds-mob/core";

export const BUILDING_LABELS: Record<BuildingId, string> = {
  main: "Hauptgebäude",
  barracks: "Kaserne",
  stable: "Stall",
  garage: "Werkstatt",
  academy: "Adelshof",
  smithy: "Schmiede",
  rally: "Versammlungsplatz",
  statue: "Statue",
  market: "Marktplatz",
  wood: "Holzfäller",
  stone: "Lehmgrube",
  iron: "Eisenmine",
  farm: "Bauernhof",
  storage: "Speicher",
  hide: "Versteck",
  wall: "Wall",
  church: "Kirche",
  watchtower: "Wachturm",
};

export const BUILDING_ICONS: Record<BuildingId, string> = {
  main: "🏛️",
  barracks: "🛡️",
  stable: "🐎",
  garage: "⚙️",
  academy: "📜",
  smithy: "🔨",
  rally: "🚩",
  statue: "🗿",
  market: "🛒",
  wood: "🌲",
  stone: "🧱",
  iron: "⛏️",
  farm: "🌾",
  storage: "📦",
  hide: "🫥",
  wall: "🧱",
  church: "⛪",
  watchtower: "🗼",
};

export const UNIT_LABELS: Record<UnitId, string> = {
  spear: "Speerträger",
  sword: "Schwertkämpfer",
  axe: "Axtkämpfer",
  archer: "Bogenschütze",
  scout: "Späher",
  lightCav: "Leichte Kavallerie",
  mountedArcher: "Berittener Bogenschütze",
  heavyCav: "Schwere Kavallerie",
  ram: "Rammbock",
  catapult: "Katapult",
  paladin: "Paladin",
  nobleman: "Adelsgeschlecht",
  militia: "Miliz",
};
